### ISSUE TITLE
Name files according to problem name

### ISSUE THREAD

**Issue by kend77** [RubenV-dev/LeetSolutions#1]
Hey @RubenV-dev, 
This is definitely a cool idea. One suggestion I have is to name each file with the name of the problem in `LeetCode` and potentially suffix it with the number. Sometimes we want to search by name and not number.

`LeetCodeSolution01.js` would become `twoSum-01.js`

**Comment by RubenV-dev** [comment]
Hey @kend77 ,
I appreciate your feedback. I definitely agree that renaming files to correspond to the appropriate problem name would be very helpful when searching for solutions. I will make the change.

**Comment by RubenV-dev** [comment]
Done. Again appreciate the feedback.
